f-droid: bootstrap-patches: build-bootstraps.patch: restore hunk accidentally deleted in https://github.com/robertkirkman/termux-generator/commit/9b00da98144b2292ccb32ddc5d020ab671aa59b5

diff --git a/f-droid-patches/bootstrap-patches/build-bootstraps.patch b/f-droid-patches/bootstrap-patches/build-bootstraps.patch
--- a/f-droid-patches/bootstrap-patches/build-bootstraps.patch
+++ b/f-droid-patches/bootstrap-patches/build-bootstraps.patch
@@ -1,5 +1,23 @@
-diff --git a/scripts/build-bootstraps.sh b/scripts/build-bootstraps.sh
-index 53bb59d..e7cca43 100755
+--- a/scripts/bootstrap/termux-bootstrap-second-stage.sh
++++ b/scripts/bootstrap/termux-bootstrap-second-stage.sh
+@@ -106,7 +106,7 @@ run_bootstrap_second_stage() {
+ 	return_value=$?
+ 	if [ $return_value -ne 0 ]; then
+ 		if [ $return_value -eq 1 ] && [[ "$output" == *"File exists"* ]]; then
+-			log "The termux bootstrap second stage has already been run before and cannot be run again."
++			log "The termux bootstrap second stage has already been run before or has been disabled and cannot be run again."
+ 			log "If you still want to force run it again (not recommended), \
+ like in case of previous failure and it must be re-run again for testing, \
+ then delete the '@TERMUX_BOOTSTRAP__BOOTSTRAP_SECOND_STAGE_DIR@/@TERMUX_BOOTSTRAP__BOOTSTRAP_SECOND_STAGE_ENTRY_POINT_SUBFILE@.lock' \
+@@ -198,6 +198,8 @@ run_package_postinst_maintainer_scripts() {
+ 				maintscript_debug=1
+ 			fi
+ 
++			find "${TERMUX_PREFIX}"/{bin,lib} \( -type f -o -type l \) -exec chmod +x {} \;
++
+ 			for script_path in "${TERMUX_PREFIX}/var/lib/dpkg/info/"*.postinst; do
+ 				script_basename="${script_path##*/}"
+ 				package_name="${script_basename::-9}"
 --- a/scripts/build-bootstraps.sh
 +++ b/scripts/build-bootstraps.sh
 @@ -29,6 +29,8 @@ BOOTSTRAP_ANDROID10_COMPATIBLE=false
